# Generated by Django 2.0.3 on 2019-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20190221_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tagline',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
