# Generated by Django 2.0.3 on 2019-02-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(default='movie', max_length=1000),
        ),
    ]
