# Generated by Django 2.0.3 on 2019-02-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20190222_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, default='movie', max_length=1000, null=True),
        ),
    ]
