# Generated by Django 2.0.3 on 2019-02-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20190222_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='slug',
        ),
    ]
