# Generated by Django 2.0.3 on 2019-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, default='movie', max_length=1000, null=True),
        ),
    ]
