# Generated by Django 2.0.3 on 2019-02-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_content_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='name',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='number',
        ),
    ]
