# Generated by Django 2.0.3 on 2019-02-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20190222_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
