# Generated by Django 2.0.3 on 2019-03-11 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20190222_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
