# Generated by Django 2.0.3 on 2019-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20190222_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='http://127.0.0.1:8000', max_length=255, null=True)),
            ],
        ),
    ]
