# Generated by Django 2.0.3 on 2019-08-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_movieserver'),
        ('content', '0022_auto_20190311_1525'),
    ]

    operations = [
    ]
