# Generated by Django 2.0.3 on 2019-08-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_merge_20190825_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchers',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watchers',
            name='paid_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
