# Generated by Django 2.0.3 on 2019-08-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20190826_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer'),
        ),
    ]
